apiVersion: v1
kind: Service
metadata:
  name: devsu-python-service
  namespace: devsu-demo
spec:
  selector:
    app: devsu-python-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
